name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: bankfliptech/deploy-to-render@v1
        with:
          serviceId: ${{ secrets.production }}
          apiKey: ${{ secrets.rnd_iP34NRwerGKgObvw0PTWO6XaZ7DD }}
          deployHookURL: ${{ secrets.https://api.render.com/deploy/srv-cen64q94reb38674f02g?key=hKXL3pKwuS0 }}
